import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";

// PMS webhook receiver
// Accepts reservation events from Mews, Cloudbeds, RMS, and generic PMS systems
// Maps reservations to guest stays with zone access

type PmsEvent = {
  event_type: "reservation.created" | "reservation.updated" | "reservation.cancelled" | "reservation.checked_in" | "reservation.checked_out";
  provider: "mews" | "cloudbeds" | "rms" | "generic";
  reservation_id: string;
  guest_name: string;
  guest_email?: string;
  guest_phone?: string;
  room_number?: string;
  check_in: string;
  check_out: string;
  status?: string;
  metadata?: Record<string, unknown>;
};

export async function POST(req: NextRequest) {
  // Verify webhook secret
  const secret = req.headers.get("x-webhook-secret") || req.headers.get("authorization")?.replace("Bearer ", "");
  if (!secret) {
    return NextResponse.json({ error: "Missing webhook secret" }, { status: 401 });
  }

  const admin = createAdminClient();

  // Find the PMS connection by webhook secret
  const { data: connections } = await admin.rpc("get_pms_connection_by_secret", { p_secret: secret });
  const connection = (connections as { id: string; org_id: string; site_id: string; provider: string; room_mapping: Record<string, string>; auto_checkin: boolean; auto_checkout: boolean }[])?.[0];

  if (!connection) {
    return NextResponse.json({ error: "Invalid webhook secret" }, { status: 401 });
  }

  let event: PmsEvent;
  try {
    const body = await req.json();

    // Normalize from different PMS formats
    if (connection.provider === "mews") {
      event = normalizeMews(body);
    } else if (connection.provider === "cloudbeds") {
      event = normalizeCloudbeds(body);
    } else {
      event = normalizeGeneric(body);
    }
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  // Map room number to zone ID
  let roomZoneId: string | null = null;
  if (event.room_number && connection.room_mapping) {
    roomZoneId = connection.room_mapping[event.room_number] || null;
  }

  // Get common area zones for this site
  const { data: zones } = await admin.rpc("get_enterprise_zones", { p_site_ids: [connection.site_id] });
  const commonZoneIds = (zones ?? [])
    .filter((z: { zone_type: string }) => ["common_area", "entrance", "parking"].includes(z.zone_type))
    .map((z: { id: string }) => z.id);

  switch (event.event_type) {
    case "reservation.created":
    case "reservation.updated": {
      // Check if stay already exists for this reservation
      const { data: existing } = await admin.rpc("get_guest_stay_by_pms_id", {
        p_site_id: connection.site_id,
        p_pms_reservation_id: event.reservation_id,
      });

      if (existing && (existing as { id: string }[]).length > 0) {
        // Update existing stay
        const stayId = (existing as { id: string }[])[0].id;
        await admin.rpc("update_guest_stay_from_pms", {
          p_stay_id: stayId,
          p_guest_name: event.guest_name,
          p_guest_email: event.guest_email || null,
          p_guest_phone: event.guest_phone || null,
          p_room_zone_id: roomZoneId,
          p_check_in: event.check_in,
          p_check_out: event.check_out,
        });
      } else {
        // Create new stay
        await admin.rpc("create_guest_stay", {
          p_site_id: connection.site_id,
          p_guest_name: event.guest_name,
          p_guest_email: event.guest_email || null,
          p_guest_phone: event.guest_phone || null,
          p_room_zone_id: roomZoneId,
          p_common_zone_ids: commonZoneIds,
          p_check_in: event.check_in,
          p_check_out: event.check_out,
          p_notes: `PMS: ${connection.provider} #${event.reservation_id}`,
        });
      }
      break;
    }

    case "reservation.checked_in": {
      if (connection.auto_checkin) {
        const { data: stays } = await admin.rpc("get_guest_stay_by_pms_id", {
          p_site_id: connection.site_id,
          p_pms_reservation_id: event.reservation_id,
        });
        if (stays && (stays as { id: string }[]).length > 0) {
          await admin.rpc("update_guest_stay_status", {
            p_stay_id: (stays as { id: string }[])[0].id,
            p_status: "checked_in",
            p_checked_in_at: new Date().toISOString(),
          });
          // Access codes would be generated by the check-in action
        }
      }
      break;
    }

    case "reservation.checked_out": {
      if (connection.auto_checkout) {
        const { data: stays } = await admin.rpc("get_guest_stay_by_pms_id", {
          p_site_id: connection.site_id,
          p_pms_reservation_id: event.reservation_id,
        });
        if (stays && (stays as { id: string }[]).length > 0) {
          await admin.rpc("update_guest_stay_status", {
            p_stay_id: (stays as { id: string }[])[0].id,
            p_status: "checked_out",
            p_checked_out_at: new Date().toISOString(),
          });
        }
      }
      break;
    }

    case "reservation.cancelled": {
      const { data: stays } = await admin.rpc("get_guest_stay_by_pms_id", {
        p_site_id: connection.site_id,
        p_pms_reservation_id: event.reservation_id,
      });
      if (stays && (stays as { id: string }[]).length > 0) {
        await admin.rpc("update_guest_stay_status", {
          p_stay_id: (stays as { id: string }[])[0].id,
          p_status: "cancelled",
        });
      }
      break;
    }
  }

  // Update last synced
  await admin.rpc("update_pms_last_synced", { p_connection_id: connection.id });

  return NextResponse.json({ ok: true, event_type: event.event_type });
}

// Normalize Mews webhook payload
function normalizeMews(body: Record<string, unknown>): PmsEvent {
  const reservation = (body.Events as Record<string, unknown>[])?.[0] || body;
  return {
    event_type: mapMewsEventType(body.Type as string || ""),
    provider: "mews",
    reservation_id: (reservation.Id || reservation.ReservationId || "") as string,
    guest_name: (reservation.GuestName || reservation.CustomerName || "Guest") as string,
    guest_email: (reservation.GuestEmail || reservation.CustomerEmail) as string | undefined,
    room_number: (reservation.RoomNumber || reservation.AssignedSpaceNumber) as string | undefined,
    check_in: (reservation.StartUtc || reservation.CheckInUtc || new Date().toISOString()) as string,
    check_out: (reservation.EndUtc || reservation.CheckOutUtc || new Date().toISOString()) as string,
  };
}

function mapMewsEventType(type: string): PmsEvent["event_type"] {
  if (type.includes("Created")) return "reservation.created";
  if (type.includes("Updated")) return "reservation.updated";
  if (type.includes("Canceled") || type.includes("Cancelled")) return "reservation.cancelled";
  if (type.includes("Started") || type.includes("CheckedIn")) return "reservation.checked_in";
  if (type.includes("Ended") || type.includes("CheckedOut")) return "reservation.checked_out";
  return "reservation.updated";
}

// Normalize Cloudbeds webhook payload
function normalizeCloudbeds(body: Record<string, unknown>): PmsEvent {
  return {
    event_type: mapCloudbbedsEventType(body.event as string || ""),
    provider: "cloudbeds",
    reservation_id: (body.reservationID || body.reservation_id || "") as string,
    guest_name: (body.guestName || body.guest_name || "Guest") as string,
    guest_email: (body.guestEmail || body.guest_email) as string | undefined,
    room_number: (body.roomNumber || body.room_number) as string | undefined,
    check_in: (body.checkInDate || body.check_in || new Date().toISOString()) as string,
    check_out: (body.checkOutDate || body.check_out || new Date().toISOString()) as string,
  };
}

function mapCloudbbedsEventType(type: string): PmsEvent["event_type"] {
  if (type.includes("new") || type.includes("create")) return "reservation.created";
  if (type.includes("modify") || type.includes("update")) return "reservation.updated";
  if (type.includes("cancel")) return "reservation.cancelled";
  if (type.includes("checkin") || type.includes("check_in")) return "reservation.checked_in";
  if (type.includes("checkout") || type.includes("check_out")) return "reservation.checked_out";
  return "reservation.updated";
}

// Generic webhook format
function normalizeGeneric(body: Record<string, unknown>): PmsEvent {
  return {
    event_type: (body.event_type || body.type || "reservation.created") as PmsEvent["event_type"],
    provider: "generic",
    reservation_id: (body.reservation_id || body.id || "") as string,
    guest_name: (body.guest_name || body.name || "Guest") as string,
    guest_email: (body.guest_email || body.email) as string | undefined,
    guest_phone: (body.guest_phone || body.phone) as string | undefined,
    room_number: (body.room_number || body.room) as string | undefined,
    check_in: (body.check_in || body.start || new Date().toISOString()) as string,
    check_out: (body.check_out || body.end || new Date().toISOString()) as string,
  };
}
